# netlify.toml at the root of your repo
[build]
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/dist"

# React Router fallback so deep links work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200